Repository Re-Freee/ReFree-iOS, pull requests merged in 2023-08, with the labels that each got.

#54 [RF-254] RFModalViewController를 Figma에 맞춰 수정
  ReFree.xcodeproj/project.pbxproj
  ReFree/Source/Common/ViewController/RFModalParentViewController.swift
  ReFree/Source/Common/ViewController/RFModalViewController.swift
  ReFree/Source/Home/ViewController/HomeViewController.swift
  ReFree/Source/KindRecipe/View/RecipeListCell.swift
  ReFree/Source/KindRecipe/ViewController/KindRecipeViewController.swift
  ReFree/Source/Recipe/ViewController/RecipeViewController.swift
  ReFree/Source/Refrigerator/ViewController/RefrigeratorViewController.swift
Labels: Feature

#55 [RF-20] 홈 화면 버튼 기능 추가
  ReFree/Resource/Assets.xcassets/refree_icon/CheckDocument.imageset/Contents.json
  ReFree/Resource/Assets.xcassets/refree_icon/CheckDocument.imageset/Image.png
  ReFree/Resource/Assets.xcassets/refree_icon/CheckDocument.imageset/Image@2x.png
  ReFree/Resource/Assets.xcassets/refree_icon/CheckDocument.imageset/Image@3x.png
  ReFree/Source/Data/Mockup/MockupData.swift
  ReFree/Source/Home/View/FoodTableViewCell.swift
  ReFree/Source/Home/View/HomeTabHeader.swift
  ReFree/Source/Home/ViewController/HomeViewController.swift
Labels: Feature

#62 RF260 진행중 - 상세 레시피 및 상세 재료 화면 연결
  ReFree/Source/Common/View/RFModal/IngredientDetailView.swift
  ReFree/Source/Common/View/RFModal/RecipeDetailView.swift
  ReFree/Source/Common/ViewController/RFModalParentViewController.swift
  ReFree/Source/Common/ViewController/RFModalViewController.swift
  ReFree/Source/Data/DTO/IngredientResponseDTO.swift
  ReFree/Source/Data/DTO/RecipeResponseDTO.swift
  ReFree/Source/Data/Repository/IngredientRepository.swift
  ReFree/Source/Data/Repository/RecipeRepository.swift
  ReFree/Source/Refrigerator/View/RefrigeratorListCell.swift
  ReFree/Source/Util/Network/DataSource/NetworkIngredient.swift
Labels: Feature

#68 [RF-292] 비밀번호 변경 API 및 화면 이동 연결
  ReFree.xcodeproj/project.pbxproj
  ReFree/Source/LogIn/View/LogInTextField.swift
  ReFree/Source/LogIn/ViewController/EmailSearchViewController.swift
  ReFree/Source/LogIn/ViewController/LogInViewController.swift
  ReFree/Source/LogIn/ViewController/PasswordChangeViewController.swift
  ReFree/Source/SignUp/ViewController/SignUpCompleteViewController.swift
  ReFree/Source/Util/Extension/UINavigationController+Init.swift
Labels: Feature

#77 fix: stastus code 200~299 허용
  ReFree/Source/Util/Network/Network.swift
Labels: Refactor

#78 Version 1.0
  ReFree.xcodeproj/project.pbxproj
  ReFree/App/Info.plist
  ReFree/Source/RegisterIngredient/View/CameraView.swift
  ReFree/Source/RegisterIngredient/View/IngredientInfoView.swift
  ReFree/Source/SignUp/ViewController/SignUpViewController.swift
Labels: Setting

#84 version 1.0.1
  ReFree.xcodeproj/project.pbxproj
Labels: Setting
